name: Polling

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Restore JBang cache
      id: cache-jbang-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.jbang
        key: ${{ runner.os }}-jbang-pPEqcqzabcxQWqKvWLXsJPKa2oapbb7

    - name: Restore reviews cache
      id: cache-reviews-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          ./reviews/
        key: ${{ runner.os }}-reviews-16dsjo3w6COWhgd0qLY8aOHStxhLWAx

    - name: Check reviews
      env:
        SEGMENT_WRITE_KEY: ${{ secrets.SEGMENT_WRITE_KEY }}
      run: |
        ./jbang vscodeReviewsWatcher.java

    - name: Save Cache
      id: cache-reviews-save
      uses: actions/cache/save@v3
      with:
        path: |
          ./reviews/
        key: ${{ steps.cache-reviews-restore.outputs.cache-primary-key }}
    
    - name: Save Cache
      id: cache-jbang-save
      uses: actions/cache/save@v3
      with:
        path: |
          ~/.jbang
        key: ${{ steps.cache-jbang-restore.outputs.cache-primary-key }}
