name: Polling

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Restore JBang cache
      id: cache-jbang-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          ~/.jbang
        restore-keys: |
          jbang-${{ hashFiles('**/*.java') }}
          jbang-
        key: jbang-${{ hashFiles('**/*.java') }}

    - name: Restore reviews cache
      id: cache-reviews-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          ./reviews/
        restore-keys: |
          reviews-${{ hashFiles('reviews/*.json') }}
          reviews-
        key: reviews-${{ hashFiles('reviews/*.json') }}

    - name: Check reviews
      env:
        SEGMENT_WRITE_KEY: ${{ secrets.SEGMENT_WRITE_KEY }}
      run: |
        ./jbang vscodeReviewsWatcher.java

    - name: Save Cache
      id: cache-reviews-save
      uses: actions/cache/save@v3
      with:
        path: |
          ./reviews/
        key: reviews-${{ hashFiles('reviews/*.json') }}
    
    - name: Save Cache
      id: cache-jbang-save
      uses: actions/cache/save@v3
      with:
        path: |
          ~/.jbang
        key: jbang-${{ hashFiles('**/*.java') }}
